// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKCaYO-BvjjUIx9zySvXd1j6-aEgEmU_4',
    appId: '1:612100607915:web:edcfcff11d5ca9eb5f8cee',
    messagingSenderId: '612100607915',
    projectId: 'flowpay-856f7',
    authDomain: 'flowpay-856f7.firebaseapp.com',
    storageBucket: 'flowpay-856f7.firebasestorage.app',
    measurementId: 'G-6K1H2PHS5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPrE8FoGO1NGTt-Bke6WjJK9OUiYJr_o',
    appId: '1:612100607915:android:48f7d643a5eba1845f8cee',
    messagingSenderId: '612100607915',
    projectId: 'flowpay-856f7',
    storageBucket: 'flowpay-856f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKz2Xt-_9rtVkdP3DShBVhSsnWbzM7c94',
    appId: '1:612100607915:ios:69ea22b30b4f61135f8cee',
    messagingSenderId: '612100607915',
    projectId: 'flowpay-856f7',
    storageBucket: 'flowpay-856f7.firebasestorage.app',
    iosBundleId: 'com.example.flowpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKz2Xt-_9rtVkdP3DShBVhSsnWbzM7c94',
    appId: '1:612100607915:ios:69ea22b30b4f61135f8cee',
    messagingSenderId: '612100607915',
    projectId: 'flowpay-856f7',
    storageBucket: 'flowpay-856f7.firebasestorage.app',
    iosBundleId: 'com.example.flowpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKCaYO-BvjjUIx9zySvXd1j6-aEgEmU_4',
    appId: '1:612100607915:web:b7d41bda0e3505a95f8cee',
    messagingSenderId: '612100607915',
    projectId: 'flowpay-856f7',
    authDomain: 'flowpay-856f7.firebaseapp.com',
    storageBucket: 'flowpay-856f7.firebasestorage.app',
    measurementId: 'G-ZHPC3FPPLK',
  );
}
